### ISSUE TITLE
Daily scrum

### ISSUE THREAD

**Issue by Irvingzhu73** [BerBer-alt/CISC327_Group8#37]
Each team member has to mention:

1 what is the branch he/she worked on (has to be pushed to the repo).
2 what is the progress so far (at least some test cases written, more than 2)
3 any difficulties.
4 what is the plan for the days before the deadline.

**Comment by BerBer-alt** [comment]
1 what is the branch he/she worked on (has to be pushed to the repo).
I worked on "YBranch4.0" branch
2 what is the progress so far (at least some test cases written, more than 2)
Input Partitioning, Input Boundary Testing and Output Partitioning
3 any difficulties. 
Finding difficult when apply Output Partitioning becasue the output of the update product function is hard to partition.
4 what is the plan for the days before the deadline.
Finish all the testing method and make sure all the test can pass.

**Comment by BrightAurora138** [comment]
1 what is the branch he/she worked on (has to be pushed to the repo).
I worked on "hwr_sprint4" branch.
2 what is the progress so far (at least some test cases written, more than 2)
Input Partitioning, Input Boundary Testing, and Output Partitioning.
3 any difficulties.
There is no difficulty.
4 what is the plan for the days before the deadline.
Make sure all tests are completed.

**Comment by Wad098** [comment]
Wade Nov.3rd
1. working on assn_4 branch
2.  
I am still parting requirements, and these tests hs been ran
-inputting existed email and password
-inputting email that is not fit the Email requirement
3.
I don't know how to write test code in python, but I am learning.
4.
finish input partition test and shotgun test tomorrow

**Comment by Irvingzhu73** [comment]
Done
